# -*- coding: utf-8 -*-
"""calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NGRFC8VJlTs8k_kBcr3xNRBjYRVLyu_H
"""

while True:
  print("=====CALCULATOR=====")
  print("Which operation do you want to perform? ")
  print("1. Addition")
  print("2. Subtraction")
  print("3. Multiplication" )
  print("4. Division")
  while True:
    choice = input("Enter your choice: ")
    if choice not in ("1", "2", "3", "4"):
      print("Please ener only 1, 2, 3 or 4.")
      continue
    break
  a = int(input("Enter first number "))
  b = int(input("Enter second number "))
  if choice == "1":
    print(a+b)
  elif choice == "2":
    print(a-b)
  elif choice == "3":
    print(a*b)
  elif choice == "4":
    print(a/b)

  print("Thank you for using calculator. ")
  while True:
    again = input("Do you want to calculate again? (yes/no) ").strip().lower()
    if again == "yes":
      break
    elif again == "no":
      print("OK THANKS")
      exit()
    else:
      print("enter only yes or no")





